### PR TITLE
Fixes for clang6

### PR DESCRIPTION
**Pull request by SolalPirelli**
A few fixes on top of the Clang6 upgrade:

- Update `build.bat` to match `build.sh`
- Fix the `size_t` issue by adding a (dubious?) heuristic
- Force the `StreamWriter` to use `\n` as a newline character, so that builds on *nix and Windows result in the same file

I still don't understand why you get `uint` and I get `int` as the underlying enum type, though.

Also, 7/10 tests fail.

### CODE REVIEW

**Comment by benpye** [comment]
Are the tests failing on Windows, Linux or both? If just Windows I would suspect it's because of Unicode handling (or lack thereof).

**Comment by SolalPirelli** [comment]
Haven't tried on Linux yet. But the failures seem like more than a few off characters. Will look into it.

**Comment by SolalPirelli** [comment]
Test failures are caused by the paths format - seems like clang doesn't like `/unix/like/absolute/paths` on Windows (even though technically they are correct syntax for an absolute path on the current drive).

Is it OK if edit the `TestVFO` infrastructure a bit to have some OS-based logic for paths? I was thinking that an easy way to do it is to add e.g. `$ROOT$` at the beginning of each path, and replace it with either an empty string (Unix) or a drive letter (Windows) during test execution.

**Comment by SolalPirelli** [comment]
I fixed the TestVFO, which uncovered Unicode-related issues; I fixed those with custom marshalling, instead of LPStr. All tests now pass on both Windows and Linux (I don't have an OS X on hand to test).

**Comment by SolalPirelli** [comment]
Fixed UTF-8 the other way around, and squashed commits a bit. I also added an .editorconfig and fixed encodings/line endings because doing clean commits was getting annoying.

**Comment by SolalPirelli** [comment]
Also made the self-generation an MSBuild task while I was at it, for cross-plat. Only thing left to do is figuring out why enums are uints on Linux and ints on Windows...

**Comment by SolalPirelli** [comment]
I still don't get the int/uint thing, and my [StackOverflow question](https://stackoverflow.com/questions/50800239/why-does-libclangs-clang-getenumdeclintegertype-return-different-results-on-lin?noredirect=1#comment88608569_50800239) got no answers, so I added a hack to force `int` if possible.

2 cross-plat differences left, related to typedefs used by getFileTime and getFileContents.

**Comment by SolalPirelli** [comment]
Done! No cross-plat differences left.

**Comment by benpye** [comment]
Thanks for this @SolalPirelli

**Pull request merged**
